apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: react:latest
          ports:
            - containerPort: 3000
      source:
        path: .
        exclude:
            - '**/jsconfig.json'